version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./scripts/generate-completions.sh

builds:
  - id: bm
    binary: bm
    main: ./cmd/bm
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - arm64  # macOS Silicon and Linux ARM64
      - amd64  # Linux x86_64
    ldflags:
      - -s -w -X github.com/farhancdr/go-bookmark/cmd.version={{.Version}}

archives:
  - id: bm
    builds:
      - bm
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os \"darwin\" }}macOS{{ else }}Linux{{ end }}_{{ if eq .Arch \"arm64\" }}ARM64{{ else }}x86_64{{ end }}"
    wrap_in_directory: true
    format: tar.gz
    files:
      - README.md
      - LICENSE
      - completions/bm.bash
      - completions/bm.zsh
      - completions/bm.fish

universal_binaries:
  - id: bm
    name_template: "{{ .ProjectName }}_{{ .Version }}_macOS_universal"

release:
  github:
    owner: farhancdr
    name: go-bookmark
  prerelease: auto

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: bm
    description: "A cross-platform CLI tool for efficient directory bookmarking and navigation"
    homepage: "https://github.com/farhancdr/go-bookmark"
    repository:
      owner: farhancdr
      name: homebrew-tools
      branch: main
      directory: Formula
    commit_author:
      name: farhancdr
      email: your-email@example.com
    install: |
      bin.install "bm"
      bash_completion.install "completions/bm.bash" => "bm"
      zsh_completion.install "completions/bm.zsh" => "_bm"
      fish_completion.install "completions/bm.fish"
    test: |
      system "#{bin}/bm", "--version"
    caveats: |
      To enable directory navigation with `bm goto`, add the following to your shell configuration:

      For Bash/Zsh (~/.bashrc or ~/.zshrc):
        function bm_goto() {
            local target_dir=$(bm goto "$1")
            if [ -n "$target_dir" ] && [ -d "$target_dir" ]; then
                cd "$target_dir"
            else
                echo "Error: $target_dir"
            fi
        }
        alias bm_g='bm_goto'

      For Fish (~/.config/fish/config.fish):
        function bm_goto
            set target_dir (bm goto $argv[1])
            if test -n "$target_dir" -a -d "$target_dir"
                cd $target_dir
            else
                echo "Error: $target_dir"
            end
        end

      After adding, reload your shell with:
        source ~/.bashrc  # or ~/.zshrc or ~/.config/fish/config.fish

      Shell completions have been installed for bash, zsh, and fish.